DROP TABLE IF EXISTS `%TABLE_PREFIX%api_key`;
CREATE TABLE `%TABLE_PREFIX%api_key` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `isactive` tinyint(1) NOT NULL default '1',
  `ipaddr` varchar(16) NOT NULL,
  `apikey` varchar(255) NOT NULL,
  `updated` datetime NOT NULL default '0000-00-00 00:00:00',
  `created` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`id`),
  UNIQUE KEY `ipaddr` (`ipaddr`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

INSERT INTO `%TABLE_PREFIX%api_key` (`id`, `isactive`, `ipaddr`, `apikey`, `updated`, `created`) VALUES (1, 1, '192.168.1.5', 'siri!', NOW(), NOW());

DROP TABLE IF EXISTS `%TABLE_PREFIX%theme`;
CREATE TABLE `%TABLE_PREFIX%theme` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `clientlogo` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `clientlogoactive` varchar(2) COLLATE utf8_bin DEFAULT NULL,
  `stafflogo` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `stafflogoactive` varchar(2) COLLATE utf8_bin DEFAULT NULL,
  `clientcolorarray` text COLLATE utf8_bin,
  `staffcolorarray` text COLLATE utf8_bin,
  `clientdefault` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '../images/logo1.png',
  `staffdefault` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '../images/logo1.png',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;    

DROP TABLE IF EXISTS `%TABLE_PREFIX%config`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `%TABLE_PREFIX%config` (
  `id` tinyint(1) unsigned NOT NULL AUTO_INCREMENT,
  `LANGUAGE_ID` int(11) NOT NULL,
  `isonline` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `timezone_offset` float(3,1) NOT NULL DEFAULT '0.0',
  `enable_daylight_saving` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `staff_ip_binding` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `staff_max_logins` tinyint(3) unsigned NOT NULL DEFAULT '4',
  `staff_login_timeout` int(10) unsigned NOT NULL DEFAULT '2',
  `staff_session_timeout` int(10) unsigned NOT NULL DEFAULT '30',
  `client_max_logins` tinyint(3) unsigned NOT NULL DEFAULT '4',
  `client_login_timeout` int(10) unsigned NOT NULL DEFAULT '2',
  `client_session_timeout` int(10) unsigned NOT NULL DEFAULT '30',
  `max_page_size` tinyint(3) unsigned NOT NULL DEFAULT '25',
  `max_open_tickets` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `max_file_size` int(11) unsigned NOT NULL DEFAULT '1048576',
  `autolock_minutes` tinyint(3) unsigned NOT NULL DEFAULT '3',
  `overdue_grace_period` int(10) unsigned NOT NULL DEFAULT '0',
  `alert_email_id` tinyint(4) unsigned NOT NULL DEFAULT '0',
  `defaultAction` varchar(128) NOT NULL,
  `default_email_id` tinyint(4) unsigned NOT NULL DEFAULT '0',
  `default_dept_id` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `default_priority_id` tinyint(2) unsigned NOT NULL DEFAULT '2',
  `default_template_id` tinyint(4) unsigned NOT NULL DEFAULT '1',
  `default_smtp_id` tinyint(4) unsigned NOT NULL DEFAULT '0',
  `spoof_default_smtp` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `clickable_urls` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `allow_priority_change` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `use_email_priority` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `enable_captcha` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `enable_auto_cron` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `enable_mail_fetch` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `enable_email_piping` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `send_sql_errors` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `send_mailparse_errors` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `send_login_errors` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `save_email_headers` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `strip_quoted_reply` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `log_ticket_activity` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `ticket_autoresponder` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `message_autoresponder` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `ticket_notice_active` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `ticket_alert_active` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `ticket_alert_admin` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `ticket_alert_dept_manager` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `ticket_alert_dept_members` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `message_alert_active` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `message_alert_laststaff` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `message_alert_assigned` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `message_alert_dept_manager` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `note_alert_active` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `note_alert_laststaff` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `note_alert_assigned` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `note_alert_dept_manager` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `overdue_alert_active` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `overdue_alert_assigned` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `overdue_alert_dept_manager` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `overdue_alert_dept_members` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `auto_assign_reopened_tickets` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `show_assigned_tickets` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `show_answered_tickets` tinyint(1) NOT NULL DEFAULT '0',
  `hide_staff_name` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `overlimit_notice_active` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `email_attachments` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `allow_attachments` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `allow_email_attachments` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `allow_online_attachments` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `allow_online_attachments_onlogin` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `random_ticket_ids` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `log_level` tinyint(1) unsigned NOT NULL DEFAULT '2',
  `log_graceperiod` int(10) unsigned NOT NULL DEFAULT '12',
  `upload_dir` varchar(255) NOT NULL DEFAULT '',
  `allowed_filetypes` varchar(255) NOT NULL DEFAULT '.doc, .pdf',
  `time_format` varchar(32) NOT NULL DEFAULT ' h:i A',
  `date_format` varchar(32) NOT NULL DEFAULT 'm/d/Y',
  `datetime_format` varchar(60) NOT NULL DEFAULT 'm/d/Y g:i a',
  `daydatetime_format` varchar(60) NOT NULL DEFAULT 'D, M j Y g:ia',
  `reply_separator` varchar(60) NOT NULL DEFAULT '-- do not edit --',
  `admin_email` varchar(125) NOT NULL DEFAULT '',
  `helpdesk_title` varchar(255) NOT NULL DEFAULT 'osTicket Support Ticket System',
  `helpdesk_url` varchar(255) NOT NULL DEFAULT '',
  `api_passphrase` varchar(125) NOT NULL DEFAULT '',
  `ostversion` varchar(16) NOT NULL DEFAULT '',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `client_motd` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `client_motd_lastupdated` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `staff_motd` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `staff_motd_lastupdated` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  KEY `isoffline` (`isonline`)
) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;


DROP TABLE IF EXISTS `%TABLE_PREFIX%department`;
CREATE TABLE `%TABLE_PREFIX%department` (
  `dept_id` int(11) unsigned NOT NULL auto_increment,
  `tpl_id` int(10) unsigned NOT NULL default '0',
  `email_id` int(10) unsigned NOT NULL default '0',
  `autoresp_email_id` int(10) unsigned NOT NULL default '0',
  `manager_id` int(10) unsigned NOT NULL default '0',
  `dept_name` varchar(32) NOT NULL default '',
  `dept_signature` tinytext NOT NULL,
  `ispublic` tinyint(1) unsigned NOT NULL default '1',
  `ticket_auto_response` tinyint(1) NOT NULL default '1',
  `message_auto_response` tinyint(1) NOT NULL default '0',
  `can_append_signature` tinyint(1) NOT NULL default '1',
  `updated` datetime NOT NULL default '0000-00-00 00:00:00',
  `created` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`dept_id`),
  UNIQUE KEY `dept_name` (`dept_name`),
  KEY `manager_id` (`manager_id`),
  KEY `autoresp_email_id` (`autoresp_email_id`),
  KEY `tpl_id` (`tpl_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

INSERT INTO `%TABLE_PREFIX%department` (`dept_id`, `tpl_id`, `email_id`, `autoresp_email_id`, `manager_id`, `dept_name`, `dept_signature`, `ispublic`, `ticket_auto_response`, `message_auto_response`, `can_append_signature`, `updated`, `created`) VALUES
(1, 0, 1, 0, 0, 'Support', 'Support Dept', 1, 1, 1, 1, NOW(), NOW()),
(2, 0, 1, 0, 0, 'Billing', 'Billing Dept', 1, 1, 1, 1, NOW(), NOW());

DROP TABLE IF EXISTS `%TABLE_PREFIX%email`;
CREATE TABLE `%TABLE_PREFIX%email` (
  `email_id` int(11) unsigned NOT NULL auto_increment,
  `noautoresp` tinyint(1) unsigned NOT NULL default '0',
  `priority_id` tinyint(3) unsigned NOT NULL default '2',
  `dept_id` tinyint(3) unsigned NOT NULL default '0',
  `email` varchar(125) NOT NULL default '',
  `name` varchar(32) NOT NULL default '',
  `userid` varchar(125) NOT NULL,
  `userpass` varchar(125) NOT NULL,
  `mail_active` tinyint(1) NOT NULL default '0',
  `mail_host` varchar(125) NOT NULL,
  `mail_protocol` enum('POP','IMAP') NOT NULL default 'POP',
  `mail_encryption` enum('NONE','SSL') NOT NULL,
  `mail_port` int(6) default NULL,
  `mail_fetchfreq` tinyint(3) NOT NULL default '5',
  `mail_fetchmax` tinyint(4) NOT NULL default '30',
  `mail_delete` tinyint(1) NOT NULL default '0',
  `mail_errors` tinyint(3) NOT NULL default '0',
  `mail_lasterror` datetime default NULL,
  `mail_lastfetch` datetime default NULL,
  `smtp_active` tinyint(1) default '0',
  `smtp_host` varchar(125) NOT NULL,
  `smtp_port` int(6) default NULL,
  `smtp_secure` tinyint(1) NOT NULL default '1',
  `smtp_auth` tinyint(1) NOT NULL default '1',
  `created` datetime NOT NULL default '0000-00-00 00:00:00',
  `updated` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`email_id`),
  UNIQUE KEY `email` (`email`),
  KEY `priority_id` (`priority_id`),
  KEY `dept_id` (`dept_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `%TABLE_PREFIX%email_banlist`;
CREATE TABLE `%TABLE_PREFIX%email_banlist` (
  `id` int(11) NOT NULL auto_increment,
  `email` varchar(255) NOT NULL default '',
  `submitter` varchar(126) NOT NULL default '',
  `added` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

INSERT INTO `%TABLE_PREFIX%email_banlist` (`id`, `email`, `submitter`, `added`) VALUES
(1, 'test@example.com', 'System', NOW());

DROP TABLE IF EXISTS `%TABLE_PREFIX%email_template`;
CREATE TABLE `%TABLE_PREFIX%email_template` (
  `tpl_id` int(11) NOT NULL auto_increment,
  `cfg_id` int(10) unsigned NOT NULL default '0',
  `name` varchar(32) NOT NULL default '',
  `notes` text,
  `ticket_autoresp_subj` varchar(255) NOT NULL default '',
  `ticket_autoresp_body` text NOT NULL,
  `ticket_notice_subj` varchar(255) NOT NULL,
  `ticket_notice_body` text NOT NULL,
  `ticket_alert_subj` varchar(255) NOT NULL default '',
  `ticket_alert_body` text NOT NULL,
  `message_autoresp_subj` varchar(255) NOT NULL default '',
  `message_autoresp_body` text NOT NULL,
  `message_alert_subj` varchar(255) NOT NULL default '',
  `message_alert_body` text NOT NULL,
  `note_alert_subj` varchar(255) NOT NULL,
  `note_alert_body` text NOT NULL,
  `assigned_alert_subj` varchar(255) NOT NULL default '',
  `assigned_alert_body` text NOT NULL,
  `ticket_overdue_subj` varchar(255) NOT NULL default '',
  `ticket_overdue_body` text NOT NULL,
  `ticket_overlimit_subj` varchar(255) NOT NULL default '',
  `ticket_overlimit_body` text NOT NULL,
  `ticket_reply_subj` varchar(255) NOT NULL default '',
  `ticket_reply_body` text NOT NULL,
  `created` datetime NOT NULL default '0000-00-00 00:00:00',
  `updated` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`tpl_id`),
  KEY `cfg_id` (`cfg_id`),
  FULLTEXT KEY `message_subj` (`ticket_reply_subj`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;


INSERT INTO `%TABLE_PREFIX%email_template` (`tpl_id`, `cfg_id`, `name`, `notes`, `ticket_autoresp_subj`, `ticket_autoresp_body`, `ticket_notice_subj`, `ticket_notice_body`, `ticket_alert_subj`, `ticket_alert_body`, `message_autoresp_subj`, `message_autoresp_body`, `message_alert_subj`, `message_alert_body`, `note_alert_subj`, `note_alert_body`, `assigned_alert_subj`, `assigned_alert_body`, `ticket_overdue_subj`, `ticket_overdue_body`, `ticket_overlimit_subj`, `ticket_overlimit_body`, `ticket_reply_subj`, `ticket_reply_body`, `created`, `updated`) VALUES
(1, 1, 'osTicket Default Template', 'Default osTicket templates', 'Support Ticket Opened [#%ticket]', '%name,\r\n\r\nA request for support has been created and assigned ticket #%ticket. A representative will follow-up with you as soon as possible.\r\n\r\nYou can view this ticket''s progress online here: %url/view.php?e=%email&t=%ticket.\r\n\r\nIf you wish to send additional comments or information regarding this issue, please don''t open a new ticket. Simply login using the link above and update the ticket.\r\n\r\n%signature', '[#%ticket] %subject', '%name,\r\n\r\nOur customer care team has created a ticket, #%ticket on your behalf, with the following message.\r\n\r\n%message\r\n\r\nIf you wish to provide additional comments or information regarding this issue, please don''t open a new ticket. You can update or view this ticket''s progress online here: %url/view.php?e=%email&t=%ticket.\r\n\r\n%signature', 'New Ticket Alert', '%staff,\r\n\r\nNew ticket #%ticket created.\r\n-------------------\r\nName: %name\r\nEmail: %email\r\nDept: %dept\r\n\r\n%message\r\n-------------------\r\n\r\nTo view/respond to the ticket, please login to the support ticket system.\r\n\r\n- Your friendly Customer Support System - powered by osTicket.', '[#%ticket] Message Added', '%name,\r\n\r\nYour reply to support request #%ticket has been noted.\r\n\r\nYou can view this support request progress online here: %url/view.php?e=%email&t=%ticket.\r\n\r\n%signature', 'New Message Alert', '%staff,\r\n\r\nNew message appended to ticket #%ticket\r\n\r\n----------------------\r\nName: %name\r\nEmail: %email\r\nDept: %dept\r\n\r\n%message\r\n-------------------\r\n\r\nTo view/respond to the ticket, please login to the support ticket system.\r\n\r\n- Your friendly Customer Support System - powered by osTicket.', 'New Internal Note Alert', '%staff,\r\n\r\nInternal note appended to ticket #%ticket\r\n\r\n----------------------\r\nName: %name\r\n\r\n%note\r\n-------------------\r\n\r\nTo view/respond to the ticket, please login to the support ticket system.\r\n\r\n- Your friendly Customer Support System - powered by osTicket.', 'Ticket #%ticket Assigned to you', '%assignee,\r\n\r\n%assigner has assigned ticket #%ticket to you!\r\n\r\n%message\r\n\r\nTo view complete details, simply login to the support system.\r\n\r\n- Your friendly Support Ticket System - powered by osTicket.', 'Stale Ticket Alert', '%staff,\r\n\r\nA ticket, #%ticket assigned to you or in your department is seriously overdue.\r\n\r\n%url/scp/tickets.php?id=%id\r\n\r\nWe should all work hard to guarantee that all tickets are being addressed in a timely manner. Enough baby talk...please address the issue or you will hear from me again.\r\n\r\n\r\n- Your friendly (although with limited patience) Support Ticket System - powered by osTicket.', 'Support Ticket Denied', '%name\r\n\r\nNo support ticket has been created. You''ve exceeded maximum number of open tickets allowed.\r\n\r\nThis is a temporary block. To be able to open another ticket, one of your pending tickets must be closed. To update or add comments to an open ticket simply login using the link below.\r\n\r\n%url/view.php?e=%email\r\n\r\nThank you.\r\n\r\nSupport Ticket System', '[#%ticket] %subject', '%name,\r\n\r\nA customer support staff member has replied to your support request, #%ticket with the following response:\r\n\r\n%response\r\n\r\nWe hope this response has sufficiently answered your questions. If not, please do not send another email. Instead, reply to this email or login to your account for a complete archive of all your support requests and responses.\r\n\r\n%url/view.php?e=%email&t=%ticket\r\n\r\n%signature', NOW(), NOW());


DROP TABLE IF EXISTS `%TABLE_PREFIX%groups`;
CREATE TABLE `%TABLE_PREFIX%groups` (
  `group_id` int(10) unsigned NOT NULL auto_increment,
  `group_enabled` tinyint(1) unsigned NOT NULL default '1',
  `group_name` varchar(50) NOT NULL default '',
  `dept_access` varchar(255) NOT NULL default '',
  `can_create_tickets` tinyint(1) unsigned NOT NULL default '1',
  `can_edit_tickets` tinyint(1) unsigned NOT NULL default '1',
  `can_delete_tickets` tinyint(1) unsigned NOT NULL default '0',
  `can_close_tickets` tinyint(1) unsigned NOT NULL default '0',
  `can_transfer_tickets` tinyint(1) unsigned NOT NULL default '1',
  `can_ban_emails` tinyint(1) unsigned NOT NULL default '0',
  `can_manage_kb` tinyint(1) unsigned NOT NULL default '0',
  `created` datetime NOT NULL default '0000-00-00 00:00:00',
  `updated` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`group_id`),
  KEY `group_active` (`group_enabled`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

INSERT INTO `%TABLE_PREFIX%groups` (`group_id`, `group_enabled`, `group_name`, `dept_access`, `can_create_tickets`, `can_edit_tickets`, `can_delete_tickets`, `can_close_tickets`, `can_transfer_tickets`, `can_ban_emails`, `can_manage_kb`, `created`, `updated`) VALUES
(1, 1, 'Admins', '1', 1, 1, 1, 1, 1, 1, 1, NOW(), NOW()),
(2, 1, 'Managers', '1', 1, 1, 0, 1, 1, 1, 1, NOW(),NOW()),
(3, 1, 'Staff', '1', 1, 0, 0, 0, 0, 0, 0, NOW(), NOW());

DROP TABLE IF EXISTS `%TABLE_PREFIX%help_topic`;
CREATE TABLE `%TABLE_PREFIX%help_topic` (
  `topic_id` int(11) unsigned NOT NULL auto_increment,
  `isactive` tinyint(1) unsigned NOT NULL default '1',
  `noautoresp` tinyint(3) unsigned NOT NULL default '0',
  `priority_id` tinyint(3) unsigned NOT NULL default '0',
  `dept_id` tinyint(3) unsigned NOT NULL default '0',
  `topic` varchar(32) NOT NULL default '',
  `created` datetime NOT NULL default '0000-00-00 00:00:00',
  `updated` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`topic_id`),
  UNIQUE KEY `topic` (`topic`),
  KEY `priority_id` (`priority_id`),
  KEY `dept_id` (`dept_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;


INSERT INTO `%TABLE_PREFIX%help_topic` (`topic_id`, `isactive`, `noautoresp`, `priority_id`, `dept_id`, `topic`, `created`, `updated`) VALUES
(1, 1, 0, 2, 1, 'Support', NOW(), NOW()),
(2, 1, 0, 3, 1, 'Billing', NOW(), NOW());

DROP TABLE IF EXISTS `%TABLE_PREFIX%kb_premade`;
CREATE TABLE `%TABLE_PREFIX%kb_premade` (
  `premade_id` int(10) unsigned NOT NULL auto_increment,
  `dept_id` int(10) unsigned NOT NULL default '0',
  `isenabled` tinyint(1) unsigned NOT NULL default '1',
  `title` varchar(125) NOT NULL default '',
  `answer` text NOT NULL,
  `created` datetime NOT NULL default '0000-00-00 00:00:00',
  `updated` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`premade_id`),
  UNIQUE KEY `title_2` (`title`),
  KEY `dept_id` (`dept_id`),
  KEY `active` (`isenabled`),
  FULLTEXT KEY `title` (`title`,`answer`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

INSERT INTO `%TABLE_PREFIX%kb_premade` (`premade_id`, `dept_id`, `isenabled`, `title`, `answer`, `created`, `updated`) VALUES
(1, 0, 1, 'What is osTicket (sample)?', '\r\nosTicket is a widely-used open source support ticket system, an attractive alternative to higher-cost and complex customer support systems - simple, lightweight, reliable, open source, web-based and easy to setup and use.', NOW(), NOW()),
(2, 0, 1, 'Sample (with variables)', '\r\n%name,\r\n\r\nYour ticket #%ticket created on %createdate is in %dept department.\r\n\r\n', NOW(), NOW());


DROP TABLE IF EXISTS `%TABLE_PREFIX%staff`;
CREATE TABLE `%TABLE_PREFIX%staff` (
  `staff_id` int(11) unsigned NOT NULL auto_increment,
  `group_id` int(10) unsigned NOT NULL default '0',
  `dept_id` int(10) unsigned NOT NULL default '0',
  `username` varchar(32) NOT NULL default '',
  `firstname` varchar(32) default NULL,
  `lastname` varchar(32) default NULL,
  `passwd` varchar(128) default NULL,
  `email` varchar(128) default NULL,
  `phone` varchar(24) NOT NULL default '',
  `phone_ext` varchar(6) default NULL,
  `mobile` varchar(24) NOT NULL default '',
  `signature` tinytext NOT NULL,
  `isactive` tinyint(1) NOT NULL default '1',
  `isadmin` tinyint(1) NOT NULL default '0',
  `isvisible` tinyint(1) unsigned NOT NULL default '1',
  `onvacation` tinyint(1) unsigned NOT NULL default '0',
  `daylight_saving` tinyint(1) unsigned NOT NULL default '0',
  `append_signature` tinyint(1) unsigned NOT NULL default '0',
  `change_passwd` tinyint(1) unsigned NOT NULL default '0',
  `timezone_offset` float(3,1) NOT NULL default '0.0',
  `max_page_size` int(11) unsigned NOT NULL default '0',
  `auto_refresh_rate` int(10) unsigned NOT NULL default '0',
  `created` datetime NOT NULL default '0000-00-00 00:00:00',
  `lastlogin` datetime default NULL,
  `updated` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`staff_id`),
  UNIQUE KEY `username` (`username`),
  KEY `dept_id` (`dept_id`),
  KEY `issuperuser` (`isadmin`),
  KEY `group_id` (`group_id`,`staff_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `%TABLE_PREFIX%syslog`;
CREATE TABLE `%TABLE_PREFIX%syslog` (
  `log_id` int(11) unsigned NOT NULL auto_increment,
  `log_type` enum('Debug','Warning','Error') NOT NULL,
  `title` varchar(255) NOT NULL,
  `log` text NOT NULL,
  `logger` varchar(64) NOT NULL,
  `ip_address` varchar(16) NOT NULL,
  `created` datetime NOT NULL default '0000-00-00 00:00:00',
  `updated` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`log_id`),
  KEY `log_type` (`log_type`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `%TABLE_PREFIX%ticket`;
CREATE TABLE `%TABLE_PREFIX%ticket` (
  `ticket_id` int(11) unsigned NOT NULL auto_increment,
  `ticketID` int(11) unsigned NOT NULL default '0',
  `dept_id` int(10) unsigned NOT NULL default '1',
  `priority_id` int(10) unsigned NOT NULL default '2',
  `topic_id` int(10) unsigned NOT NULL default '0',
  `staff_id` int(10) unsigned NOT NULL default '0',
  `email` varchar(120) NOT NULL default '',
  `name` varchar(32) NOT NULL default '',
  `subject` varchar(64) NOT NULL default '[no subject]',
  `helptopic` varchar(255) default NULL,
  `phone` varchar(16) default NULL,
  `phone_ext` varchar(8) default NULL,
  `ip_address` varchar(16) NOT NULL default '',
  `status` enum('open','closed') NOT NULL default 'open',
  `source` enum('Web','Email','Phone','Other') NOT NULL default 'Other',
  `isoverdue` tinyint(1) unsigned NOT NULL default '0',
  `isanswered` tinyint(1) unsigned NOT NULL default '0',
  `duedate` datetime default NULL,
  `reopened` datetime default NULL,
  `closed` datetime default NULL,
  `lastmessage` datetime default NULL,
  `lastresponse` datetime default NULL,
  `created` datetime NOT NULL default '0000-00-00 00:00:00',
  `updated` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`ticket_id`),
  UNIQUE KEY `email_extid` (`ticketID`,`email`),
  KEY `dept_id` (`dept_id`),
  KEY `staff_id` (`staff_id`),
  KEY `status` (`status`),
  KEY `priority_id` (`priority_id`),
  KEY `created` (`created`),
  KEY `closed` (`closed`),
  KEY `duedate` (`duedate`),
  KEY `topic_id` (`topic_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `%TABLE_PREFIX%ticket_attachment`;
CREATE TABLE `%TABLE_PREFIX%ticket_attachment` (
  `attach_id` int(11) unsigned NOT NULL auto_increment,
  `ticket_id` int(11) unsigned NOT NULL default '0',
  `ref_id` int(11) unsigned NOT NULL default '0',
  `ref_type` enum('M','R') NOT NULL default 'M',
  `file_size` varchar(32) NOT NULL default '',
  `file_name` varchar(128) NOT NULL default '',
  `file_key` varchar(128) NOT NULL default '',
  `deleted` tinyint(1) unsigned NOT NULL default '0',
  `created` datetime NOT NULL default '0000-00-00 00:00:00',
  `updated` datetime default NULL,
  PRIMARY KEY  (`attach_id`),
  KEY `ticket_id` (`ticket_id`),
  KEY `ref_type` (`ref_type`),
  KEY `ref_id` (`ref_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `%TABLE_PREFIX%ticket_lock`;
CREATE TABLE `%TABLE_PREFIX%ticket_lock` (
  `lock_id` int(11) unsigned NOT NULL auto_increment,
  `ticket_id` int(11) unsigned NOT NULL default '0',
  `staff_id` int(10) unsigned NOT NULL default '0',
  `expire` datetime default NULL,
  `created` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`lock_id`),
  UNIQUE KEY `ticket_id` (`ticket_id`),
  KEY `staff_id` (`staff_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `%TABLE_PREFIX%ticket_message`;
CREATE TABLE `%TABLE_PREFIX%ticket_message` (
  `msg_id` int(11) unsigned NOT NULL auto_increment,
  `ticket_id` int(11) unsigned NOT NULL default '0',
  `messageId` varchar(255) default NULL,
  `message` text NOT NULL,
  `headers` text,
  `source` varchar(16) default NULL,
  `ip_address` varchar(16) default NULL,
  `created` datetime NOT NULL default '0000-00-00 00:00:00',
  `updated` datetime default NULL,
  PRIMARY KEY  (`msg_id`),
  KEY `ticket_id` (`ticket_id`),
  KEY `msgId` (`messageId`),
  FULLTEXT KEY `message` (`message`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `%TABLE_PREFIX%ticket_note`;
CREATE TABLE `%TABLE_PREFIX%ticket_note` (
  `note_id` int(11) unsigned NOT NULL auto_increment,
  `ticket_id` int(11) unsigned NOT NULL default '0',
  `staff_id` int(10) unsigned NOT NULL default '0',
  `source` varchar(32) NOT NULL default '',
  `title` varchar(255) NOT NULL default 'Generic Intermal Notes',
  `note` text NOT NULL,
  `created` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`note_id`),
  KEY `ticket_id` (`ticket_id`),
  KEY `staff_id` (`staff_id`),
  FULLTEXT KEY `note` (`note`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `%TABLE_PREFIX%ticket_priority`;
CREATE TABLE `%TABLE_PREFIX%ticket_priority` (
  `priority_id` tinyint(4) NOT NULL auto_increment,
  `priority` varchar(60) NOT NULL default '',
  `priority_desc` varchar(30) NOT NULL default '',
  `priority_color` varchar(7) NOT NULL default '',
  `priority_urgency` tinyint(1) unsigned NOT NULL default '0',
  `ispublic` tinyint(1) NOT NULL default '1',
  PRIMARY KEY  (`priority_id`),
  UNIQUE KEY `priority` (`priority`),
  KEY `priority_urgency` (`priority_urgency`),
  KEY `ispublic` (`ispublic`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

INSERT INTO `%TABLE_PREFIX%ticket_priority` (`priority_id`, `priority`, `priority_desc`, `priority_color`, `priority_urgency`, `ispublic`) VALUES
(1, 'low', 'Low', '#DDFFDD', 4, 1),
(2, 'normal', 'Normal', '#FFFFF0', 3, 1),
(3, 'high', 'High', '#FEE7E7', 2, 1),
(4, 'emergency', 'Emergency', '#FEE7E7', 1, 0);

DROP TABLE IF EXISTS `%TABLE_PREFIX%ticket_response`;
CREATE TABLE `%TABLE_PREFIX%ticket_response` (
  `response_id` int(11) unsigned NOT NULL auto_increment,
  `msg_id` int(11) unsigned NOT NULL default '0',
  `ticket_id` int(11) unsigned NOT NULL default '0',
  `staff_id` int(11) unsigned NOT NULL default '0',
  `staff_name` varchar(32) NOT NULL default '',
  `response` text NOT NULL,
  `ip_address` varchar(16) NOT NULL default '',
  `created` datetime NOT NULL default '0000-00-00 00:00:00',
  `updated` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`response_id`),
  KEY `ticket_id` (`ticket_id`),
  KEY `msg_id` (`msg_id`),
  KEY `staff_id` (`staff_id`),
  FULLTEXT KEY `response` (`response`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `%TABLE_PREFIX%timezone`;
CREATE TABLE `%TABLE_PREFIX%timezone` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `offset` float(3,1) NOT NULL default '0.0',
  `timezone` varchar(255) NOT NULL default '',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

INSERT INTO `%TABLE_PREFIX%timezone` (`id`, `offset`, `timezone`) VALUES
(1, -12.0, 'Eniwetok, Kwajalein'),
(2, -11.0, 'Midway Island, Samoa'),
(3, -10.0, 'Hawaii'),
(4, -9.0, 'Alaska'),
(5, -8.0, 'Pacific Time (US & Canada)'),
(6, -7.0, 'Mountain Time (US & Canada)'),
(7, -6.0, 'Central Time (US & Canada), Mexico City'),
(8, -5.0, 'Eastern Time (US & Canada), Bogota, Lima'),
(9, -4.0, 'Atlantic Time (Canada), Caracas, La Paz'),
(10, -3.5, 'Newfoundland'),
(11, -3.0, 'Brazil, Buenos Aires, Georgetown'),
(12, -2.0, 'Mid-Atlantic'),
(13, -1.0, 'Azores, Cape Verde Islands'),
(14, 0.0, 'Western Europe Time, London, Lisbon, Casablanca'),
(15, 1.0, 'Brussels, Copenhagen, Madrid, Paris'),
(16, 2.0, 'Kaliningrad, South Africa'),
(17, 3.0, 'Baghdad, Riyadh, Moscow, St. Petersburg'),
(18, 3.5, 'Tehran'),
(19, 4.0, 'Abu Dhabi, Muscat, Baku, Tbilisi'),
(20, 4.5, 'Kabul'),
(21, 5.0, 'Ekaterinburg, Islamabad, Karachi, Tashkent'),
(22, 5.5, 'Bombay, Calcutta, Madras, New Delhi'),
(23, 6.0, 'Almaty, Dhaka, Colombo'),
(24, 7.0, 'Bangkok, Hanoi, Jakarta'),
(25, 8.0, 'Beijing, Perth, Singapore, Hong Kong'),
(26, 9.0, 'Tokyo, Seoul, Osaka, Sapporo, Yakutsk'),
(27, 9.5, 'Adelaide, Darwin'),
(28, 10.0, 'Eastern Australia, Guam, Vladivostok'),
(29, 11.0, 'Magadan, Solomon Islands, New Caledonia'),
(30, 12.0, 'Auckland, Wellington, Fiji, Kamchatka');

DROP TABLE IF EXISTS `%TABLE_PREFIX%languages`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `%TABLE_PREFIX%languages` (
  `LANGUAGE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ABBREVIATION` text NOT NULL,
  `LANGUAGE_NAME` text NOT NULL,
  `LANGUAGE_NATIVE_NAME` text NOT NULL,
  `DIRECTION` text NOT NULL,
  `CODEPAGE` text NOT NULL,
  `ALERT_EXCESSIVE_LOGIN_ATTEMPTS_BY_CLIENT` text NOT NULL,
  `ERROR_ACCESS_DENIED_INVALID_TICKET` text NOT NULL,
  `ERROR_EMAIL_PARSE_FAILED` text NOT NULL,
  `ERROR_FILE_REJECTED` text NOT NULL,
  `ERROR_INVALID_FROM_ADDRESS` text NOT NULL,
  `ERROR_INVALID_FILE_TYPE` text NOT NULL,
  `ERROR_MESSAGE_REQUIRED` text NOT NULL,
  `ERROR_NAME_REQUIRED` text NOT NULL,
  `ERROR_OCCURED` text NOT NULL,
  `ERROR_OCCURED_TRY_AGAIN` text NOT NULL,
  `ERROR_POSSIBLY_INVALID_TICKET` text NOT NULL,
  `ERROR_SERVICES_NOT_AVAILABLE` text NOT NULL,
  `ERROR_SECURITY_REPEAT_RESULT_LOCK` text NOT NULL,
  `ERROR_SECURITY_VIOLATION_YOUR_ACCOUNT_WILL_LOCKED` text NOT NULL,
  `ERROR_UNABLE_SEND_MESSAGE_TRY_AGAIN` text NOT NULL,
  `ERROR_UNABLE_TO_POST_THE_RESPONSE` text NOT NULL,
  `ERROR_UNKNOWN_ACTION` text NOT NULL,
  `ERROR_UNABLE_TO_POST_MESSAGE` text NOT NULL,
  `ERROR_YOU_HAVE_REACHED_MAXIMUM_FAILED_LOGIN` text NOT NULL,
  `ERROR_YOU_MUST_CHANGE_PASSWORD` text NOT NULL,
  `ERROR_SEARCH_TERM_MORE_3` text NOT NULL,
  `LABEL_ACTIVE_IN_PARENTHESIS` text NOT NULL,
  `LABEL_ADD_NEW_DEPT` text NOT NULL,
  `LABEL_ADMIN_DASHBOARD` text NOT NULL,
  `LABEL_ADMIN_PANEL` text NOT NULL,
  `LABEL_ADVANCED` text NOT NULL,
  `LABEL_APPEND` text NOT NULL,
  `LABEL_APPEND_SIGNATURE` text NOT NULL,
  `LABEL_ALL` text NOT NULL,
  `LABEL_ALL_DEPARTMENTS` text NOT NULL,
  `LABEL_API` text NOT NULL,
  `LABEL_ASSIGN` text NOT NULL,
  `LABEL_ASSIGN_TO_STAFF` text NOT NULL,
  `LABEl_ASSIGNED_TICKETS` text NOT NULL,
  `LABEL_ASC` text NOT NULL,
  `LABEL_ASCENDING` text NOT NULL,
  `LABEL_ATTACHMENT` text NOT NULL,
  `TITLE_CLOSED_TICKETS` text NOT NULL,
  `TITLE_OPEN_PREVIOUS_TICKET` text NOT NULL,
  `TITLE_OFFLINE` text NOT NULL,
  `TITLE_MY_PREFERENCES` text NOT NULL,
  `TITLE_BAR_OFFLINE` text NOT NULL,
  `TITLE_BOX_NEW_TICKET` text NOT NULL,
  `TITLE` text NOT NULL,
  `TEXT_WELCOME_BACK` text NOT NULL,
  `TEXT_WELCOME_MSG` text NOT NULL,
  `TEXT_WELCOME_TITLE` text NOT NULL,
  `TEXT_WELCOME_BACK_STAFF` text NOT NULL,
  `TEXT_WELCOME_BACK_CLIENT` text NOT NULL,
  `TEXT_WELCOME_BACK_VACATION` text NOT NULL,
  `TEXT_YOUVE_REACHED_MAXIMUM_FAILED_LOGIN_ATTEMPTS_ALLOWED` text NOT NULL,
  `TEXT_VISIBLE_TO_CLIENT` text NOT NULL,
  `TEXT_VIEW_TICKET` text NOT NULL,
  `TEXT_VIEW_CLOSED` text NOT NULL,
  `TEXT_VIEW_OPEN` text NOT NULL,
  `TEXT_USED_FOR_OUTGOING_EMAILS` text NOT NULL,
  `TEXT_UPDATE_TICKET` text NOT NULL,
  `TEXT_UNABLE_CREATE_TICKET` text NOT NULL,
  `TEXT_THANKS_NEW_TICKET` text NOT NULL,
  `TEXT_TICKETS_STATUS` text NOT NULL,
  `TEXT_TICKET_WILL_REOPEN_NEW_POST` text NOT NULL,
  `TEXT_TICKET_UPDATED_SUCCESSFULLY` text NOT NULL,
  `TEXT_TICKET_TRANSFERED_SUCESSFULLY_TO_DEPT` text NOT NULL,
  `TEXT_TICKET_THREAD` text NOT NULL,
  `TEXT_TICKET_STATUS_SET_TO_OPEN` text NOT NULL,
  `TEXT_TICKET_STATUS_CHANGED_TO` text NOT NULL,
  `TEXT_TICKET_STATUS` text NOT NULL,
  `TEXT_TICKET_NUMBER` text NOT NULL,
  `TEXT_TICKET_NUM_STATUS_SET_CLOSED` text NOT NULL,
  `TEXT_TICKET_FLAGGED_AS_OVERDUE` text NOT NULL,
  `TEXT_TICKET_DELETED_FOREVER` text NOT NULL,
  `TEXT_TICKET_CREATED_SUCCESSFULLY` text NOT NULL,
  `TEXT_TICKET_CREATED` text NOT NULL,
  `TEXT_TICKET_ASSIGNED_TO_STAFF` text NOT NULL,
  `TEXT_TOTAL_MY_TICKETS` text NOT NULL,
  `TEXT_TOTAL_ANSWERED_TICKETS` text NOT NULL,
  `TEXT_TOTAL_OPEN_TICKETS` text NOT NULL,
  `TEXT_SUPPORT_CENTER` text NOT NULL,
  `TEXT_SUPPORT_TICKET_SISTEM` text NOT NULL,
  `TEXT_SUPPORT_TEAM` text NOT NULL,
  `TEXT_SYSTEM_IS_OFF_LINE` text NOT NULL,
  `TEXT_SEARCH_RESULTS` text NOT NULL,
  `TEXT_SHOW_ZERO` text NOT NULL,
  `TEXT_SHOW_FROM_TO_OF_ALL` text NOT NULL,
  `TEXT_SORT_BY_PRIORITY` text NOT NULL,
  `TEXT_SORT_BY_TICKET_ID` text NOT NULL,
  `TEXT_SORT_BY_SUBJECT` text NOT NULL,
  `TEXT_SORT_BY_DEPARTMENT` text NOT NULL,
  `TEXT_SORT_BY_DATE` text NOT NULL,
  `TEXT_SORT_BY_CATEGORY` text NOT NULL,
  `TEXT_SESSION_TIMED_OUT_DUE_TO_INACTIVITY` text NOT NULL,
  `TEXT_SELECT_TARGET_DEPT` text NOT NULL,
  `TEXT_SELECT_STAFF_MEMBER` text NOT NULL,
  `TEXT_SELECT_PREMADE_REPLY` text NOT NULL,
  `TEXT_SELECT_DEPARTMENTS_GROUP_MEMBERS` text NOT NULL,
  `TEXT_RESPONSE_POSTED_SUCCESSFULLY` text NOT NULL,
  `TEXT_REQUIRED_WHEN_DEPT_IS_PUBLIC` text NOT NULL,
  `TEXT_REFRESH` text NOT NULL,
  `TEXT_PRIORITY_CHANGED_SUCCESSFULLY` text NOT NULL,
  `TEXT_PLEASE_TAKE_A_MINUTE_TO_DELETE_INSTALL` text NOT NULL,
  `TEXT_PLEASE_FILL_FORM_NEW_TICKET` text NOT NULL,
  `TEXT_PLEASE_FILL_STAFF_FORM_BELOW_OPEN_NEW_TICKET` text NOT NULL,
  `TEXT_POST_REPLY` text NOT NULL,
  `TEXT_OF_SELECTED_TICKETS_DELETED` text NOT NULL,
  `TEXT_OF_SELECTED_TICKETS_MARKED_OVERDUE` text NOT NULL,
  `TEXT_OF_SELECTED_TICKETS_CLOSED` text NOT NULL,
  `TEXT_OF_SELECTED_TICKETS_REOPENED` text NOT NULL,
  `TEXT_OFFLINE_MODE_WILL_DISABLE_CLIENT` text NOT NULL,
  `TEXT_OFFLINE` text NOT NULL,
  `TEXT_OVERDUE` text NOT NULL,
  `TEXT_OVERDUE_TICKETS` text NOT NULL,
  `TEXT_OVERDUE_STATS` text NOT NULL,
  `TEXT_OPEN` text NOT NULL,
  `TEXT_OPEN_TICKETS` text NOT NULL,
  `TEXT_OPEN_PREVIOUS_TICKET` text NOT NULL,
  `TEXT_OPEN_NEW_TICKET` text NOT NULL,
  `TEXT_NO_TICKETS_FOUND` text NOT NULL,
  `TEXT_NEW_TICKET_AUTO_RESPONSE` text NOT NULL,
  `TEXT_NOT_THIS_USER` text NOT NULL,
  `TEXT_NEW_TICKET` text NOT NULL,
  `TEXT_MY_ACCOUNT` text NOT NULL,
  `TEXT_MY_TICKETS_STATS` text NOT NULL,
  `TEXT_MY_TICKETS` text NOT NULL,
  `TEXT_LOG_OUT` text NOT NULL,
  `TEXT_LOGIN_VIEW_STATUS_OF_TICKET` text NOT NULL,
  `TEXT_INVALID_FILE_TYPE` text NOT NULL,
  `TEXT_INVALID_LOGIN` text NOT NULL,
  `TEXT_INTERNAL_NOTE_POSTED` text NOT NULL,
  `TEXT_HELPDESK_ENABLE_CRON_CALL_ON_STAFF_ACTIVITY` text NOT NULL,
  `TEXT_HELPDESK_CLIENT_MAX_IDLE_TIME_IN_MINUTES` text NOT NULL,
  `TEXT_HELPDESK_STAFF_MAX_IDLE_TIME_IN_MINUTES` text NOT NULL,
  `TEXT_HEADER_TITLE` text NOT NULL,
  `TEXT_HOME` text NOT NULL,
  `TEXT_GLOBAL_AUTO_RESPONSE_SETTINGS` text NOT NULL,
  `TEXT_GLOBAL_THERMO_NUCLEAR_WAR` text NOT NULL,
  `TEXT_GENERAL_INQUIRY` text NOT NULL,
  `TEXT_FORGOT_YOUR_LOGIN_INFO` text NOT NULL,
  `TEXT_FILE_IS_TOO_BIG` text NOT NULL,
  `TEXT_FILE_REJECTED` text NOT NULL,
  `TEXT_EXCESSIVE_LOGIN_ATTEMPTS_BY_CLIENT` text NOT NULL,
  `TEXT_EXCESSIVE_LOGIN_ATTEMPTS` text NOT NULL,
  `TEXT_ENTER_MESSAGE` text NOT NULL,
  `TEXT_EMAIL_REMOVED_FROM_BANLIST` text NOT NULL,
  `TEXT_EMAIL_ADDRESS_USED_SEND_AUTO_RESPONSES` text NOT NULL,
  `TEXT_EMAIL_ADDED_TO_BANLIST` text NOT NULL,
  `TEXT_DEPT_UPDATED_SUCCESSFULLY` text NOT NULL,
  `TEXT_DEPT_TRANSFER` text NOT NULL,
  `TEXT_DEPT_DEPENDS_ON_EMAIL` text NOT NULL,
  `TEXT_CREATE_FAILED` text NOT NULL,
  `TEXT_COMMENTS_REASONS_TRANSFER` text NOT NULL,
  `TEXT_CLOSED` text NOT NULL,
  `TEXT_CLOSED_TICKETS` text NOT NULL,
  `TEXT_CAN_BE_APPENDED_TO_RESPONSES` text NOT NULL,
  `TEXT_BOX_NEW_TICKET` text NOT NULL,
  `TEXT_ATTACH_FILE` text NOT NULL,
  `TEXT_ANY_STATUS` text NOT NULL,
  `TEXT_AUTHENTICATION_REQUIRED_QUESTION` text NOT NULL,
  `TEXT_AUTHENTICATION_REQUIRED` text NOT NULL,
  `TEXT_ASSIGNED_TICKETS` text NOT NULL,
  `TEXT_AND_TICKET_STATUS_SET_TO_CLOSED` text NOT NULL,
  `TEXT_AND_STATUS_SET_TO` text NOT NULL,
  `TEXT_ANSWERED_TICKETS` text NOT NULL,
  `TEXT_ANSWERED_STATS` text NOT NULL,
  `TEXT_ALL_DEPARTMENTS` text NOT NULL,
  `TEXT_ACCESS_DENIED` text NOT NULL,
  `LABEL_VIEW_STATUS` text NOT NULL,
  `LABEL_USERS` text NOT NULL,
  `LABEL_USERNAME` text NOT NULL,
  `LABEL_UPDATE_DEPARTMENT` text NOT NULL,
  `LABEL_UPDATE_DATE` text NOT NULL,
  `LABEL_TYPE` text NOT NULL,
  `LABEL_TRANSFER` text NOT NULL,
  `LABEL_TOGGLE` text NOT NULL,
  `LABEL_TO` text NOT NULL,
  `LABEL_TICKET_STATUS` text NOT NULL,
  `LABEL_TICKET_SOURCE` text NOT NULL,
  `LABEL_TICKET_NUMBER` text NOT NULL,
  `LABEL_TICKET_ID` text NOT NULL,
  `LABEL_TICKET` text NOT NULL,
  `LABEL_TELEPHONE` text NOT NULL,
  `LABEL_SYSTEM_SETTINGS` text NOT NULL,
  `LABEL_SYSTEM_PREFERENCES_AND_SETTINGS` text NOT NULL,
  `LABEL_SYSTEM_LOGS` text NOT NULL,
  `LABEL_SYSTEM_DEFAULT_TEMPLATE` text NOT NULL,
  `LABEL_SUBMIT_TICKET` text NOT NULL,
  `LABEL_SUBMIT` text NOT NULL,
  `LABEL_SUBJECT` text NOT NULL,
  `LABEL_STATUS` text NOT NULL,
  `LABEL_STAFF_PANEL` text NOT NULL,
  `LABEL_STAFF_MEMBERS` text NOT NULL,
  `LABEL_STAFF_MEMBER` text NOT NULL,
  `LABEL_STAFF` text NOT NULL,
  `LABEL_SORT_BY_UPDATE_DATE` text NOT NULL,
  `LABEL_SORT_BY_TITLE` text NOT NULL,
  `LABEL_SORT_BY` text NOT NULL,
  `LABEL_SETTINGS` text NOT NULL,
  `LABEL_SELECT_TEMPLATE` text NOT NULL,
  `LABEL_SELECT_SOURCE` text NOT NULL,
  `LABEL_SELECT_PRIORITY` text NOT NULL,
  `LABEL_SELECT_ONE_EMAIL` text NOT NULL,
  `LABEL_SELECT_ONE_TOPIC` text NOT NULL,
  `LABEL_SELECT_MANAGER_OPTIONAL` text NOT NULL,
  `LABEL_SELECT_DEPARTMENT` text NOT NULL,
  `LABEL_SELECT` text NOT NULL,
  `LABEL_SEARCH_FOR` text NOT NULL,
  `LABEL_SEARCH` text NOT NULL,
  `LABEL_REPLY_TITLE` text NOT NULL,
  `LABEL_RESULTS_PER_PAGE` text NOT NULL,
  `LABEL_RESET` text NOT NULL,
  `LABEL_REOPEN_TICKET` text NOT NULL,
  `LABEL_REOPEN` text NOT NULL,
  `LABEL_RE_ASSIGN_TICKET` text NOT NULL,
  `LABEL_QUERY_RETURNED_ZERO_RESULT` text NOT NULL,
  `LABEL_QUERY` text NOT NULL,
  `LABEL_PREMADE_REPLIES` text NOT NULL,
  `LABEL_PRIMARY_OUTGOING_EMAIL` text NOT NULL,
  `LABEL_PRIORITY` text NOT NULL,
  `LABEL_PREFERENCES` text NOT NULL,
  `LABEL_POST_REPLY` text NOT NULL,
  `LABEL_POST_INTERNAL_NOTE` text NOT NULL,
  `LABEL_PHONE` text NOT NULL,
  `LABEL_PASSWORD_AGAIN` text NOT NULL,
  `LABEL_PASSWORD` text NOT NULL,
  `LABEL_PAGE` text NOT NULL,
  `LABEL_PRIVATE_HIDDEN` text NOT NULL,
  `LABEL_PRIVATE` text NOT NULL,
  `LABEL_PUBLIC` text NOT NULL,
  `LABEL_OVERDUE` text NOT NULL,
  `LABEL_OUTGOING_EMAIL` text NOT NULL,
  `LABEL_OTHER` text NOT NULL,
  `LABEL_OPEN_NEW_TICKET` text NOT NULL,
  `LABEL_OPEN_TICKET` text NOT NULL,
  `LABEL_OPEN` text NOT NULL,
  `LABEL_NOTE_TITLE` text NOT NULL,
  `LABEL_NONE` text NOT NULL,
  `LABEL_NO_MANAGER_ADD_USERS` text NOT NULL,
  `LABEL_NEW_TICKET_PRIORITY` text NOT NULL,
  `LABEL_NEW_TICKET` text NOT NULL,
  `LABEL_NEW_PREMADE_REPLY` text NOT NULL,
  `LABEL_NEW_MESSAGE` text NOT NULL,
  `LABEL_NEW_DEPARTMENT` text NOT NULL,
  `LABEL_NAME` text NOT NULL,
  `LABEL_MY_SIGNATURE` text NOT NULL,
  `LABEL_MY_PROFILE` text NOT NULL,
  `LABEL_MY_PREFERENCE` text NOT NULL,
  `LABEL_MY_ACCOUNT` text NOT NULL,
  `LABEL_MONTH` text NOT NULL,
  `LABEL_MONTHS` text NOT NULL,
  `LABEL_MESSAGE` text NOT NULL,
  `LABEL_MANAGER` text NOT NULL,
  `LABEL_MAKE_PRIVATE` text NOT NULL,
  `LABEL_MAKE_PUBLIC` text NOT NULL,
  `LABEL_LAYOUT` text NOT NULL,
  `LABEL_LAST_FETCHED` text NOT NULL,
  `LABEL_LAST_UPDATED` text NOT NULL,
  `LABEL_LOG_OUT` text NOT NULL,
  `LABEL_KNOWLEDGE_BASE_PREMATE` text NOT NULL,
  `LABEL_KNOWLEDGE_BASE` text NOT NULL,
  `LABEL_ISSUE_SUMMARY` text NOT NULL,
  `LABEL_HELPDESK_URL` text NOT NULL,
  `LABEL_HELPDESK_SYSTEM_LOG_LEVEL` text NOT NULL,
  `LABEL_HELPDESK_STATUS` text NOT NULL,
  `LABEL_HELPDESK_STAFF_SESSION_TIMEOUT` text NOT NULL,
  `LABEL_HELPDESK_STAFF_EXCESSIVE_LOGINS` text NOT NULL,
  `LABEL_HELPDESK_SELECT_DEFAULT_TEMPLATE` text NOT NULL,
  `LABEL_HELPDESK_SELECT_DEFAULT_DEPARTMENT` text NOT NULL,
  `LABEL_HELPDESK_DEFAULT_PAGE_SIZE` text NOT NULL,
  `LABEL_HELPDESK_PURGE_LOGS_AFTER` text NOT NULL,
  `LABEL_HELPDESK_PURGE_NONE_DISABLE` text NOT NULL,
  `LABEL_HELPDESK_PENALTY_IN_MINUTES` text NOT NULL,
  `LABEL_HELPDESK_NONE_DISABLE_LOGGER` text NOT NULL,
  `LABEL_HELPDESK_NAME_TITLE` text NOT NULL,
  `LABEL_STAFF_MOTD` text NOT NULL,
  `LABEL_CLIENT_MOTD` text NOT NULL,
  `LABEL_HELPDESK_MAKE_URLS_CLICKABLE` text NOT NULL,
  `LABEL_HELPDESK_ENABLE_AUTO_CRON` text NOT NULL,
  `LABEL_HELPDESK_DEFAULT_EMAIL_TEMPLATES` text NOT NULL,
  `LABEL_HELPDESK_DEFAULT_DEPARTMENT` text NOT NULL,
  `LABEL_HELPDESK_CLICKABLE_URLS` text NOT NULL,
  `LABEL_HELPDESK_CLIENT_SESSION_TIMEOUT` text NOT NULL,
  `LABEL_HELPDESK_CLIENT_EXCESSIVE_LOGINS` text NOT NULL,
  `LABEL_HELPDESK_BIND_STAFF_SESSION_TO_IP` text NOT NULL,
  `LABEL_HELPDESK_ATTEMPT_ALLOWED_BEFORE_A` text NOT NULL,
  `LABEL_HELP_TOPICS` text NOT NULL,
  `LABEL_HELP_TOPIC` text NOT NULL,
  `LABEL_GO` text NOT NULL,
  `LABEL_GENERAL_SETTINGS` text NOT NULL,
  `LABEL_FULL_NAME` text NOT NULL,
  `LABEL_FROM` text NOT NULL,
  `LABEL_ENTER_NOTE_CONTENT` text NOT NULL,
  `LABEL_ENABLE_SYSTEM_OFF_LINE` text NOT NULL,
  `LABEL_EMAIL_TEMPLATES` text NOT NULL,
  `LABEL_EMAIL_ADDRESS` text NOT NULL,
  `LABEL_EMAILS_SETTINGS` text NOT NULL,
  `LABEL_EMAILS` text NOT NULL,
  `LABEL_EMAIL` text NOT NULL,
  `LABEL_DIRECTORY_STAFF` text NOT NULL,
  `LABEL_DIRECTORY` text NOT NULL,
  `LABEL_DISABLED_IN_PARENTESIS` text NOT NULL,
  `LABEL_DESCENDING` text NOT NULL,
  `LABEL_DESC` text NOT NULL,
  `LABEL_DEPT_TYPE` text NOT NULL,
  `LABEL_DEPT_SIGNATURE` text NOT NULL,
  `LABEL_DEPT_EMAIL_ABOVE` text NOT NULL,
  `LABEL_DEPT_EMAIL` text NOT NULL,
  `LABEL_DEPT_NAME` text NOT NULL,
  `LABEL_DEPT_ACCESS` text NOT NULL,
  `LABEL_DEPT` text NOT NULL,
  `LABEL_DEPT_MANAGER_NONE` text NOT NULL,
  `LABEL_DEPT_MANAGER` text NOT NULL,
  `LABEL_DEPARTMENTS` text NOT NULL,
  `LABEL_DEPARTMENT` text NOT NULL,
  `LABEL_DELETE_DEPT_S` text NOT NULL,
  `LABEL_DELETE` text NOT NULL,
  `LABEL_DEFAULT` text NOT NULL,
  `LABEL_DATE_SPAN` text NOT NULL,
  `LABEL_DATE` text NOT NULL,
  `LABEL_DASHBOARD` text NOT NULL,
  `LABEL_CREATE_DATE` text NOT NULL,
  `LABEL_CLOSED` text NOT NULL,
  `LABEL_CHECK_STATUS` text NOT NULL,
  `LABEL_CHANGE_PASSWORD` text NOT NULL,
  `LABEL_CATEGORY_DEPT` text NOT NULL,
  `LABEL_CATEGORY` text NOT NULL,
  `LABEL_CANNED_RESPONSE` text NOT NULL,
  `LABEL_CANCEL` text NOT NULL,
  `LABEL_CLOSED_TICKETS` text NOT NULL,
  `LABEL_CLOSED_TICKET` text NOT NULL,
  `LABEL_CLOSE` text NOT NULL,
  `LABEL_BASIC` text NOT NULL,
  `LABEL_AUTORESP` text NOT NULL,
  `LABEL_AUTORESPONDERS` text NOT NULL,
  `LABEL_AUTO_RESPONSE_EMAIL` text NOT NULL,
  `LABEL_ATTACHMENTS` text NOT NULL,
  `LABEL_CLOSE_TICKET` text NOT NULL,
  `LABEL_STATUS_IS` text NOT NULL,
  PRIMARY KEY (`LANGUAGE_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `toro_languages`
--

LOCK TABLES `%TABLE_PREFIX%languages` WRITE;
/*!40000 ALTER TABLE `toro_languages` DISABLE KEYS */;
INSERT INTO `%TABLE_PREFIX%languages` VALUES (1,'us','English','English','ltr','UTF-8','Excessive login attempts by a client','Access Denied. Possibly invalid ticket ID','Email parse failed','File {0} rejected!','Invalid FROM address','Invalid File Type','Message required','Name required','Error(s) occured. Please try again','Error(s) occured. Please try again','Access Denied. Possibly invalid ticket ID','Services not available!','Security violation. Repeated violations will result in your account being locked.','Security violation. Repeated violations will result in your account being locked','Unable to post the message. Try again','Unable to post the response','Unknown Action','Unable to post the message. Try again','You have reached maximum failed login attempts allowed.  Try again after 5 minutes.','You must change your password to continue.','Search term must be more than 3 chars','(Active)','Add New Dept.','Dashboard','Admin Panel','Advanced','Append','Append Signature','All','A
 ll Departments','API','Assign','Assign to Staff','Assigned Tickets','ASC','Ascending','Attachment','Closed Tickets','Open Previous Ticket','Support Ticket System Offline','My Preferences','Support Ticket System','New Ticket','toro <||> Ticketing System','Welcome back','In order to streamline support requests and better serve you, we utilize a support ticket system. Every support request is assigned a unique ticket number which you can use to track the progress and responses online. For your reference we provide complete archives and history of all your support requests.','Welcome to the support center.','Welcome back, <strong>{0}</strong>','Welcome back, <strong>{0}</strong>','Welcome back! You are listed as on vacation. Please let an admin or your manager know that you are back.','You have reached maximum failed login attempts allowed.','Visible to client/customer.','View Ticket','View Closed','View Open','Used for outgoing emails,alerts and notices to user and staff.','Upd
 ate Ticket #{0}','Unable to create a ticket. Please correct errors below and try again!','Thank you for contacting us.<br>A support ticket request has been created and a representative will be getting back to you shortly if necessary.','Tickets Status','Ticket will be reopened on message post','Ticket updated successfully','Ticket transfered sucessfully to {0} Dept.','Ticket Thread','Ticket status set to OPEN','Ticket status changed to {0}','Ticket Status','Ticket #','Ticket #{0} status set to CLOSED','Ticket flagged as overdue','Ticket Deleted Forever','Ticket created successfully','Support ticket request created','Ticket Assigned to {0}','My Tickets ({0})','Answered ({0})','Open ({0})','Support Center','<span>SUPPORT TICKET</span> SYSTEM','Support Team','<strong>System is set to offline mode</strong> - Client interface is disabled and ONLY admins can access staff control panel.','Search Results','Showing 0 (zero)','Showing {0} - {1} of {2}','Sort by Priority','Sort By Tick
 et ID','Sort By Subject','Sort By Department','Sort By Date','Sort By Category','Session timed out due to inactivity','-Select Target Dept-','-Select Staff Member.-','Select a premade reply','Select departments group members are allowed to access in addition to thier own department.','Response Posted Successfully','Required when Dept is public','Refresh','Priority Changed Successfully','Please take a minute to delete <strong>setup/install</strong> directory for security reasons.','Please fill in the form below to open a new ticket.','Please fill in the form below to open a new ticket.','Post Reply','{0} of {1} selected tickets deleted','{0} of {1} selected tickets marked overdue','{0} of {1} selected tickets closed','{0} of {1} selected tickets reopened','Offline mode will disable client interface and <b>only</b>','Thank you for your interest in contacting us.<br>','Overdue','Overdue Tickets','Overdue ({0})','Open','Open Tickets','Check status of previously opened ticket. we
  provide archives and history of all your support requests complete with responses.','Open new Ticket','NO tickets found.','An email with the ticket number has been sent to <b>{0}</b>.You will need the ticket number along with your email to view ticket status and progress online.<br><br>If you wish to send additional comments or information regarding same issue, please follow the instructions on the email.','I am not this user','New Ticket','My Account','My Tickets ({0})','My Tickets','Log Out','To view the status of a ticket, provide us with your login details below.<br/>','Invalid file type [ {0} ]','Invalid login','Internal note posted','Enable cron call on staff','(<i>Client','(<i>Staff','toroTS <||> Support Ticket System','Home','Global auto-response settings in preference section must be enabled for Dept Enable setting to take effect.','Do you want to play a game?','General Inquiry','Forgot your login info? Please <a href=\"open.php\">open a new ticket</a>.','File is t
 oo big. Max {0} bytes allowed','File [ {0} ] rejected','Excessive login attempts (client)','Excessive login attempts','Enter Message','Email removed from banlist','Email address used to send auto-responses, if enabled.','Email ({0}) added to banlist','Dept updated successfully','Dept. Transfer','Dept depends on email & help topics settings for incoming tickets.','Create Failed ','Comments/Reasons for the transfer. Â (<i>Internal note</i>)','Closed','Closed Tickets','can be appended to responses.Â (available as a choice for public departments)','Submit a new support request. Please provide as much detail as possible so we can best assist you. To update a previously submitted ticket, please use the form to the right. A  valid email address is required.','Attach File','Any status','Authentication Required?','Authentication Required','Assigned Tickets',' & ticket status set to closed',' and status set to {0}','Answered Tickets','Tickets Respondidos ({0})','All Departments','Acce
 ss Denied','View Status','Users','Username','Update Department','Last Updated','Type','Transfer' ers (Add Users)','New Ticket Priority','New Ticket','New Premade Reply','New Message','New Department','Name','My Signature','My Profile','My Preference','My Account','Month','Months','Message','Manager','Make Privae','Make Public','Layout','Last Fetched','Last Updated','Log Out','Knowledge Base: Premade','Kowledge Base','Issue Summary','Helpdesk URL','System Log Level','Helpdesk Status','Staff Session Timeout','Staff Excessive Logins','Select Default Template','Select Default Dept.','Default Page Size','Purge logs after','None (Disable)','min. timeout (penalty in minutes)','None (Disable Logger)','Helpdesk Name/Title','Staff Message of the Day','Client Message of the Day','Make URLs clickable','Enable A nable','Email Templates','Email Address','E-Mails Settings','E-Mails','E-Mail','Staff Directory','Directory','(Disabled)','Descending','DESC','Dept. Type','Dept. Signature','Dept. E ','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''/*!40000 ALTER TABLE `toro_languages` ENABLE KEYS */;
UNLOCK TABLES;
